function mostrarSenha() {
    var str = document.getElementById("botaoMostrarSenha").innerHTML;
    var arr = str.split(" ");
    var res = arr[0];

    var campoAutenticacaoSenha = document.getElementById("senha");

    /* botaoMostrarSenha.innerHTML = "visibility_off"; */


    if (res == "visibility") {
        botaoMostrarSenha.innerHTML = "visibility_off";
        campoAutenticacaoSenha.setAttribute('type', 'text');
    }
    else {
        botaoMostrarSenha.innerHTML = "visibility";
        campoAutenticacaoSenha.setAttribute('type', 'password');
    }

}

function confirmar() {
    var senha = document.getElementById('senha').value;
    var arr = senha.split(" ");
    var camposenha = arr[0];

    var senhaDefinida = "123"

    if (camposenha == senhaDefinida) {
        var autenticacao = document.getElementById('autenticacao');
        autenticacao.className = "autenticacaoOcultar";

        var links = document.getElementById('links');
        links.className = "linksExibir";
    }
    else {
        window.alert("Prezado(a)!!\n\nVerifique se a senha digitada está correta.\nEm caso de dúvida entre em contato com a TE.\n\nE-mail: te@unisuam.edu.br")
    }

}

$("table input").keyup(function () {
    var index = $(this).parent().index();
    var nth = "table td:nth-child(" + (index + 1).toString() + ")";
    var valor = $(this).val().toUpperCase();
    $("table tbody tr").show();
    $(nth).each(function () {
        if ($(this).text().toUpperCase().indexOf(valor) < 0) {
            $(this).parent().hide();
        }
    });
});



var exibirProva = document.getElementById('exibirProva');

$('#GADM1069').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfgmaujzb0od6g_uYU-ngKQoi835DOLGoz1A-iJ9yKGUZNHfA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADM1041').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSc_ToKryOGLuypaUFhSoNp9FrsBAT4RGxzPKSNY6iEgc86y_A/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADS1053').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdCToHPiJp7bfYkA7wgUAGz3nv26zUG6TLR82Py1rRDphWWWw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GSER1105').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScvc1-ElRCfVS1p319eBD74TizgZChbxNpwnCGy0laDprHMsw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1084').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdcG1yBA3Mi6qOAd7IYsJMtyOBBbzISWjXnsCglOvwHSSidQw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GENG1130').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScjY3yN-ouUv0x_--Kzpm6zC5sB5IgGtA-5UTT3qjFcci4krQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GENG1031').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSd8-KQfD28gM_yvOc0tF-iAN3oRIbK1xP_IbIlKUDTk6RzcbQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GENG1068').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf_bcOwLh6IwCaWEnKEUd2f6u3NxkSonWGHsqJ-gbrL4tcKhA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GENG1081').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScVkyRCvikccsykfSfXo_am3My9yrdcb8TvPpzal9UJMmgAyA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1079').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScNVNhM2KgNqFCSvxRrh2I2uq2MRi3DPCXFWwpulcJBhzyfvg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCSA1059').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScX9SNYwFFLP06-rDtcGiwcIUSyn7o0FpQ0SjkNJ9Z9JwSEMg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1044').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe36VWZuPksfYqD8D6S5IstNV30YQmFfF0kDt9PA5h3-iZwQA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1041').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSePpDp1mK_LEuwDhOJMLdhM9wOzt4UAclC5DAHeMTiPASSdfw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1039').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdGKvL-LNfmKKTrRQFveyiBATygPzCxq3eIcJHPRC9fr4bIIA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1047').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfqlaAONVU5237TRbl9KT4VDAPp3z825GiiBi5QaV8q8dX7qA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1043').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScRaQ6mBuwOklLVKR3Xin4HlvBQAauKWsgPE-957R7zVI2jNA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADM1047').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdSAqGq5SDWjIV6-8PDbhpDL7vTrW8hSNIIG_3RN8Zmt0SL6Q/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADM1074').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdJ-z5NtFECX0AoXpC1D0RJIq4i-tNK4FxJkz4ytyTZmI8ELA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0100').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfcgrwJwyIoNjMuR-QyCANgpehH5lE4VxUpVZZNhkbXVmQMGw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDBI0003').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSc6flpAnHAvzyz5IKgEKxTFZu6m41GlmcvJKr81zPT26npxFA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GINS1010').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSemrR93VS2ArhM6FzahdZlSnZTgfl7DaDSQleRngd6UQztxiQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1070').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfcankdaLMahknLhzf0x4lVWSOJhR_k5H7ufCd-3U1Z5tcHAw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0003').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdnU1-bfh-OEljEEVbMRxlv03Ku15LMsLy6PO-xt4e_g7I2DQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0197').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSd1GQLieO7kWrR27K0LDQZ2qbXEha2minS3sQvXD7qGdDTnBg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0204').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfWxTf5o79Sc1q1MNcgZ770faPkCPpEFwyIZ9DbMqPcmCkyJA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0098').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScpseEshDRelx33UuOUeVeQFSPTPDZfXRxjhv3pdOwc4b7DfQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0198').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdmKadJHnWtvYJHZhO7dSJKBVXPU77T-ndiY7DS3vjy-74fIw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0104').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdqQKBwzM4S6lkVWYnxqJzrDJ5hYGryQhgpnK3FcbggB89crA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0065').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdRDZUZ0_39AS-5f3Cm_PVg76cB3VQUedXRxtFtvX7_0bGX8A/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0200').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf4ytLTypZG6r2NkYInQsxTJ9OdxJtnZE7Dvpad5VdJfeHFVQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0199').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfU2oaZIEhP6pzYxcckgnctIUMcUBipRnuBh0j47oGD7OpALA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GMKT1048').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe4R_-HhVffH7_1YLYWpeOiQNA5U6dS1QzqU3DgPBb-R9Y3Qw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCSA1047').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScQDb2lc0LJ4FbA7JTesZfOVoXq-ksNIagf6P4i995SBFZKVQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GSER1034').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScuZDfKnciisa48PlowslMI-Zh9pAyg2o2HHG7JU8E6rKbHhQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0015').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfuUnyZknv-RiC42avX40unpwQPSNOZSMfGsGz4xBJxhzLOKA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GSER1032').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScEhl1JS7ZQw2O4yxRbGIL0rm037V3mKBvF0tKpErbrPs1amQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GSER1038').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfLB7WAc_0IhMMC2Ef1uQogTy5w9ilBn9tRM2lo3nCmtZWqRw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GSER1036').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScFIu5IzrJ1ejw1-UDqmqjHb5f8b6qHfZCJOlSD9cBxX5ETAQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADS1042').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfW5u0KKVSa1tgaAsgTq1hX7HNQU0biZ2wzeQbqULl_Ac0S6A/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GHBD0037').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeHaWTOVB3ciIpPNfjhXPj7HVX78Ym4Q8uHwlNp2i4rsiuasw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GBIO1055').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf2zbDXBSm52rEJxOeZRp0HEuqBqWOR5MFRjQq8OGBW_HiyRA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GECO1023').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSc-hKr4yiSUnY0bEp1DqqAz97pvQTfsAhdo8Tb86T8H9-dZVQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDEF0009').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdClEvLJrI84ONbw1X6ConEteTAHrtJ6tvwLj6B-Eub7xD13w/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GPED1054').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfjH3lD-S26kF5DbIXUAVHe4MlBQWVi_QzmhvVn4U4iPx39tg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GPED1118').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf4BTs2gejVoFbIkDRUT0ZlLBZcAfG_71jxYbSVD6_RhUNgYw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GHBD0029').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScxa4mO6CCBC9fVWvYSsea-nOziqJhABPo4HpcKcDkEq3n7Tw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0081').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSddMqf4oe-BeWlrGyzhN_MF8uc1ZlEk_X6LSdlpwLslzMu82g/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GRED1005').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSccMZ5BTO0HEHh-U_x-d209e_RfF2URyn1Svv8thrqpSrJJEQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0059').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf6yIYm7_YCwvQUYJK2L32cs-TcdF9YSDkJ3mx4Qiu9ZQ4ppw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0182').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScnuLDAYkueNAomNvxnbNKM3ZiNGUiLO14LU32aQmdyKpo9rQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADS1040').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeR-f61SGH4skWOX6m6X98SUui_dlj5lFqAAEQcmK8s-eoHEg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0020').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfo0ugxJTxkG_59aMahtWYLFxqahnincThYR8ijR5U1sqiCKQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0092').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdtGU-VNeyJEQbweBeDQs3hF_JI4tcODdfQMrwlSWw59tH38w/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0111').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScNTBVSvxCcaBBDCtPkYN8w95Ftpa6dG2-Bcy9xjkOOgqiZZg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0166').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSduGrFraq0tlv5W8UjKJ7iAUJCbOntK06Fm1TwVMoPKeqyHzg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GINF1092').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeJMKztX0jtQMKTGOKxAjnLFC49HaBiMTyvaMLdE0N6zM9E1A/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GFTO1081').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdalvOSyi-GSrH39_z4r5hOjMnSg2VDWNtxSJJA9DLEBvjlrA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GGAM1017').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdb1nwce6dr5vVdE9km0Mli1JE2d9ztON60MDZBn7ag1Us4lA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0087').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeGWk-0MO3KLM3HuAXvfVAuxMlFli6ki2eg-C0PZOb7gh_vqQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0021').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSc6-g63mniZeO4nIxmxMkkGl0Fwc_KzWNFnlJ46Wb3s03LjXA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0093').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSd29jgAE9_1blmhxlhKIXY9ZgzFSLvud6LWQPj5Ru_NaAlSMA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0088').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeKU0xGVljT2unnt_P9MdyWMt-r9h4wYOI7D1YmxpOM8tjwMA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GENG1131').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeAyalWM1SfO4iok0NHTPrZsw-7MAFyO3q42mHNB06xQJmaGw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0082').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdbVmHX8y7pjL1strAFjEyRsrcfDegVL6wWMI3oMGF0QHFNdw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0022').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfiuEWmFZk7SI3WHk1JvVypw1AXh-5h-QgWphnHieZ_VDiCjw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GSER1097').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfGLuhA-ehxgxsuXam_M5IVosgqkwTGIUNRySqda7F773IFug/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GPED1123').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdiRR8Gv55bdNg0eO8pA2oWr2MEDbJhme7FxjBAH2ZcY-hc9A/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GJOR1071').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfWu3ujwfMIFFQWYT0HjxsNKa9t4i8qIzv5Ztkq5gurCppsBg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0185').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScqUMx2R8tbrH7NlI_Oiqp8h1yWQWxvAXgVmRzAq4lQjRt6xQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GSER1046').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdEHPOqKzf51872S0ab85BlXqFYapTgFTH7v2OdgI89Va44BA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0091').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfw0S9bxVpeCHYJJIr5jvCZdGbFKbF9oxcKAfML9bQ2dR7J-w/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GARQ1154').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScawDkTrgMPi0UI87KN-EuUzlWbf4nza3OG0sJiEqQW7-1qXg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDIR1154').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfd0-kAVS835xif11bQrczsB2IpqCuxEL-ze8z3F5YlfMQmgQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCSA1078').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSc-Il0j8OymGGR4mv5Vx6uVeXaXkDFrh5us0yKEvF9SFtUyag/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0094').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeINvhZ3hfTHUI4StcZtUhWNjavAlf9tbpMt88zwBdFhJbByA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCSA1079').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeR_zku_n-zzgtmmBXT_wlXV7NXPVrbadzxwH76TZog9VI9pw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GPED1001').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeBSJ9eGxTFRtuybRdXp39Zq3RK-Nxeo-cdfudj_9AfrWhgvw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCSA1069').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe08rtUpnN7gMq_Ph8fbXc1WEH3MMDcpGUZjWHZI4NcBEa9vw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GPED1120').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScnui0WLpmIPdxSMX0Y6wdpezG83TACAyGCJpNVtlFW4x6qfg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0096').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdutn8hoYmpi5nq3giEs53EQAgN_FpHZFfpbjkUmnYnnv6D3A/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GMKT1045').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfrDrH_-51I1vRSHsM5YOwSSRoaTEH5w10ghHa7u1uhAwX4rA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0086').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe-BS5E5zqPllG47X2YItkj_NVwb3Ad42dZfmVpEeXbvbZEMQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0097').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSebVxzrgpIdOzADaSop3tqdl-37JRR48KT6Mll1uU-G5LYlxA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GMKT1064').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScj9B62P0OSc32vuhdaqu09hB2c4vhRUs5UMbpA0vhZ4QmIsw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0105').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeRhmmHfsfkBlpLR0lQfF7yA3z5w-g5Ff0SO35VgCEhav6EEA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCSA1011').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdBPPNCS9Obh_5VDdvG-6Zy4h5MqajwvycFLZ_5Oce2m9Diug/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCSA1057').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfNCAG5tH7di1cvymlkvMBucKr8BLPIsrZ110xvZ3DtbGUPKw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0165').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSd_xfhJ_OTW6jQq33E1fdi-Lz0GVt1Oyl-5Fb6xCBDufBXPzA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0113').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSflEPu7z7j8xYMX7Lb7K84MobLTe5ZWHXqc_5Ebwpz1b8JonQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1046').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdDwuZrCgcPKi1Q0-K5R0m3ktwDU1BKvekfuaXPsZZTFGGzDw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDAI0002').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf_2FkCRRcvTtwZwhL1J5ijzDTCnEkMNtHE34qplmkfQ8wFBw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GSER1103').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeoE-moIaF6WieXzTmum7XeoUeFBXCl6wK85YL8-vozRMs-Ug/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GPED1182').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe1klsjJIkdSEEjEbpPomz9VMaP_S1VXtIRvPL8JxBs-5bHTA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GPED1064').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSccLdjElYRa29btrcvgee2KkVj99gLhb7DcS188Vz-ndWesMA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GPED1057').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeCQveI_d7z3AKDb-wD2WfxIMKE_1fxmHPIbJc-mpW9hlN9Cg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GINS1001').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSffBgtjdNUZAeALkvCh1SeehzsHuX7tEE_i_73l16sj2jQlPQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GINS1022').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScn8lOTzHcMequqTgOCXACOURSiigNzoHuZs54EJtq_x78xBw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0208').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScJziKCtJBC_9ZQpq8wBD5oe7gML_j4mZlbHtRZHG6QwhLLWQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GPED1181').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScQuI9kp18BxCAybvPb8N2F2b84Sy_oMgJhblGI3sOJaS_EqA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GPED1048').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSc_aX_PhGjdUcJ6ZSh8NIuQTDJHaXaAkaWhC3zHhuGRNv07mw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GINS1002').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdwnz5tYZsDyExhaTzuNYCeOwN1NzrcNzBo8gr_gcyys2OZzg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GINS1029').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSepT4AJUUPK0N_y6aCv1v7jSDMum8Hy_P1_ZqpMBDDJqb4woQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0190').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfjTegIw3vnCTtLAbV2jhr3AekHV5LAdUofR1RbjjRtYWvetg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0063').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeMtpLR2_M2u_OjGLsoE_ZKq9aIOJXzvFMtK4-lgLgiBXc6Zg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0193').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdgNuUCu3ajCp2XVcFfz-coz1gytAn6I8AuF86Gr8ZYXad3aA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GGAM1018').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeeyOnDK0TdiCIoc3Af8lk5Kp0-O3gzhkLJY4bgRSkYuG39VA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0032').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScsodRaibv0nclliKkpshJRudkcURRVOyLWUdhEeDBPcUA3sQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0033').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSes5AUQ1uIAGeY-BeNDsK9pP_JoCiQ7GWngzHQJYfdH_Wwkog/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0034').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfdpAr9Q3l3Cl3kdHuyBdcBGYOB4m0n03hmH861ZGFNeqo4BQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GPED1046').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSecyZG6uLWiFfrQPR7ExToWxeHwN5vymU7uwiGBfY7xDKl0Vw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0043').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScfaEbKm_9f8PKg8nXTMh-PjIvGL5K5cksIZs34N6zBMiOAcw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GINS1006').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScA2Oyam771anIomBwiCxb1QNFa7mCb7ulYNQvmIfZnwIzYMg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GINS1032').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeIfkUeAtyH9XOfo97QCVeSbdAiQYnrtu3xPaxTRVHdHcxFVQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GENF1076').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeI6CqJXjUWkPVX4b0Dkd4Cfxs5WRyQRjR8QrvtYzD3tgRTaQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#EAD00186').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScmEQ4t9Bdy2ECmUSk4v-KgVZGDvi5d9llI-0xiFKEqsb49nw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GSER1043').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfQGQoq6giAbVSvLVEPRCsKY7gDSSydOgZVOsH9Aa8uUj00hQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0151').click(function(){exibirProva.src = "https://docs.google.com/forms/d/1gktTmurv4S1BmXSWzG26c9TlE5iAgaV5piEHDLX1Pck/edit";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GSER1044').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdxa8y3cKC99HBxPGi7ezsK4Si1VKE7pd_YQho7_QyQWQMo7Q/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GSER1106').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScR4qszikbBEJQwA6Y5Wtuaa8WzR9Hz9EAfWWGTCT6fTf5gag/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GGAM1025').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf1EjLmdaKpAUD0moqVvNiZ2hbAt3IvejwEC120v39zZgGRXQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADM1085').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfV45TEoGt5H3Ne_N3N5fpzwp4OlvLdYHJbsjf_AZfT3afu-w/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADM1043').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSd8489c69aKCDFg2Fr703OzrsA_DcApRaMl_QtMXQ9hEeNhmQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0146').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfsNLFtw4pL4Pc0N9LtmH7yJ1NHXiGs-Li4trbq6fZv3k8TLQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADS1057').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeolkaSv8zovgactmMq4rn7EpDhdLdrSDjUFvbosgAydT1HBg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GGAM1027').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdBMZAak-DS9eKkFqJnXsCqQ-qI3hgqyC7IbJoyhWdQnGTkmA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADS1050').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfx_O8vqRWBj83PC9LtmDiuvO2m_hMDYc_HY06BqKTlTeueLg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDBI0008').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScE8xq4Yp3Tinj0gL5A6LxDppL3zNsGLQdQhSNxpjMiTs4M2A/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0084').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfwKGk8PkXzgBThKopMLcUsDNAZFyehB8FqH1r8AH69ssSb_g/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GSOC1003').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdtfhlTpWhw_Na_OtPKC4HIRKiss2fj5GQ37-pkqRJVaatDIA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GARQ1168').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfBs93kseWvwP0Kkdr_DOjS_oV_GiAlj1dseaSqP21qe5giHw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0001').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScoOqrcvqBe4D1fWxf2HZdDRqyQTs74_p8cJdgZvmrBNUo7QA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0203').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfCXXFsFDDX34BI10gIsPaqfDJbTsbSBaWY2mA4hMAgIc348A/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0035').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSd1G_QMn9vY6LOzlIUYB2kSfsaCxLBZzyrqsaQSIpTL5SVJGQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0192').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScc4U8UtwtxkqjjYssaZrnyq2VNhliAmgIIonAqsLO-93rHYA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADS1059').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfnGo77_XSwoq6TTMcha_V_1M6Agoo1v8hPWk9mnMtR4GwgzQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0106').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe_xVh-3SAGQFkFa4-5BZdCjaX3xT4BOXJ0iS7RYKLLVyC_3g/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0107').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe5jqE6CJOe8up4gn4PXRDi3G7p4dg_0JnJFfEEn_bAVIV5-w/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GLIC1019').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSd4-6uniI5evI2FpuuUzkKARQarnJDKVWbEB_igXvV8VBdZJg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0036').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdQHN_jUHvY5zMsVsXXzaL7TTUq4r3Grb3C-iNXRCAvfvT04w/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0044').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfIURA67U_eskiX9YTL-mzsURq5VnsK-O0L9TFFH7dwjtHHpg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GHBD0002').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe0Q7wB7qpRqE_gff51bPOBigGYqoYwuy6U2nm5fHHCk9GTEQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDEF0015').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeaHiaiX8_sAvmb0TmEWiYcF2votsS6RgljOdBuyLtN-kRT_A/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDIR1177').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe8EkCZroxeC9z19_SwoXKAXn0DCZ5lavldMtiG-SyEN2o5gw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0210').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeyPfw-syVk39yeOOi1kUZZLpCqK06uvwCppH4Raa6Af7gx1g/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDBI0012').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdNnm-mZWBI0qoHLjnZniH_N8VVpKkQXpIBWx_329Zg60icbA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1076').click(function(){exibirProva.src = "https://docs.google.com/forms/d/18i6-qL5URmHyjM-fBxbZGf5JLGDYxn65jYjYPWdbhtU/edit";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0207').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScgzn6QLtqDvFCOzdHdQC6Zd_1EQ6yxVMD18AuYvKVW96Vypg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1080').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeTObzEy1huci2v-4eYNxPaZh6EOAkNRcnG_sHEpgDI09hijQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCSA1045').click(function(){exibirProva.src = "https://docs.google.com/forms/d/1pqec0T80CB6AIKoarhyfmXV55hvE4ysqDj79SCb6uI0/edit";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0158').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScOIxphsROQSITxvY2bIbZpDB6GpE2Yeo2zMbKQpdCjT4jixQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0186').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSekGhcG0nSbqn8bjW0EHpkD9XwNAM2GumoUsrA6SBQoJQoCHw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0070').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScUpY9Lztez3r--n7Whojqi9OUTSqwmws3C-f6VUN23N-OhHQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDEP0011').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeI-v-T-D8UJdQkqbIqSHK279p5Awp5LR4o0VGGMoW_J8XofQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDEP0008').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdZv1dpAcDd_GhNliUHVROTphcrvyKvB61OYBaxNx67d_xtjQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDLO0003').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeSqmJlHci_yyFcy2HxGzHIWGiACbOhFszoiRrNynes4Xp1Yw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDBI0010').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeiRMjOufHYTRzMCs4_2Gd0rvZim5OsuHq0sWCe7zFf_5rJcQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GARQ1159').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSd37YQIYLjRR664XFOHAqA11LJEQLMGYeXk7SLaBffm7CbYXQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0102').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe9pjHR2yaqK6ePYz0c29SrkdrkJ5C8UPDIjWOFg3QqM2f9Ug/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GPRO1045').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdOeCSFf0dzjpSyKyMRTtvO5a3Ng6Bdt0Rkp44GVxf6fWQ2AQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCSA1049').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeFK0VwXq4YC4QOSSIXDHu6Zhlhh9Wuhgk2WF6BehPO1JsghA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0132').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfFghwtDDkR6O7CLAEhhKhiSjaHjsu2KqJq071IbN97p7MP3Q/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0133').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScKRZPenkrflkI3mvARjmoDsOUlGldP8U3RfzPzeINPWF8Bkg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0169').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdkmyzqtbsGmkG1IdRXgAaw-UsS5rcjGvVx0xukNaqZWCIN4w/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDPU0003').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScjFxUUIdaVNhaTbMU54S7TckjEac55HNtp8DfdaDftdY6J8g/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0173').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSexFATagm2zs6lV66aM2UhTaW5UaliPP3iRc-A5fBVrxhDCjQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0172').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeBzbT0JIFoLhoecs0wezHNox3G5PUlw-zjELWNbRjkSWtBCA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0134').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSd0goGBhgf8KRy6Uy8ChdjD71Bf6j3jWoKHSbn7jzQrfvobNw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDLO0002').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSc9rrtE2ICsHCFF7kvhNFMFPQCwQU0xMCivsZB5OtgLi1yjPg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0159').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScfAhQnUwnYnPIlQ7fTWUDNLwb-JwVl7xnJsnfCxaV6MV80aw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GPED1047').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdbqwCttbblQLQnwaUsnMk2bAeBk25ev8W0x8MNWp8DcEovPg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1074').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdJygkx8cHd3XSqg41n3GCrI7hRKlgfXtoFlPM1i_PXqHGw9w/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1075').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfRIdp-t3Z5DnjA1mtIC9NhhDpsh8uvmsL3brQaCxp4aJSwcg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1089').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfWO7Qci00fxdpUrfVn0RBoIdDx47LeHWdBJu1lwTrFuFtYzQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1072').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdeNNTBfANL2Uf8ixNvZyGDJefKN9ZKdQjjo6DopvrDY1WsHg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCOB1048').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfzoX4V29UxvCtJuEA7O5iJXlswnZQgcA_ho3yyUQsXkahd5Q/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0152').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdng6yq1A4zM_P-6A_J995GzoKKfV1D8XCnAuQ5-XNkJbSAVQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GGHO0002').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfZkslwfi6gMBPQagNkoNIvHZLd51nNRposR2IW5Fw-m_5--g/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDLL0002').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdCpVA-ctXoH2MXi0rteVuO_cLkzRruJ-7IISbZH7ZhlvGcww/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDLL0004').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSc6vbzvalCpkzMb_DpJJ62ecxsDUS2U5Ujp3U04gjZ2tMkxyw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDLL0003').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe3OOmKgmKPkDl3RIaGBlKXQ0Xa_nq8qqoyWHlQmfAxHW9vug/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDLL0005').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScEAKiSMNzoRYk3uFxXFX7ZJO2sm-f-k570iJ3sELK-5uiO0Q/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GINS1019').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfLovQM8nNYxvPh360972pcIn0FaEuOSDsZdfiELIjp0vMTKw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADM1073').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdOibtY38Mu7_1e1ATJ3dVUBk03iSpqfPTG3J4C8bS66ymmjg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GGRH1048').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSceK4qMnQXb0a62dQ4dEB55yjU-peABFOd2p2W7yM8jogBB6A/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0069').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSekztnA94sm4kA1rWAcaxTYyfaetAe1AXmG50qEzoHJaOPaNg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GGHO0001').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeprwuCAmfy_Xmxfu6AaMHmAlXUIco9F9_VHznET4oMA7tfdA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADM1075').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeAr99CMXwopFnEMb5YBPU73w1VK2W91WI11GLQYgz5zMG2nA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GENG1109').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdLDmugEm3JqBj7Ga5pew5ifkV6--VcHm3tcDqvOwMPPRGr-A/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDBI0013').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeVK8Bw2-RtYEClwELISzNwC8_rtl8GWPWioTsp0NCOHCQnrw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDBI0014').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf5Pym1FP_WTOrvdGUhbhnU0HNcDH--_Az7tJUTMqWUrEq5NQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#EAD00176').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfCvT6oNG8YKB-AXxy3jp0LEIvhJE7SX5-wjulbuE_mMiYr8Q/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0163').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfI9kz-BwNFxdGoFBeE4Zf-81TqhuufX_xeUqwFVVHzv20TKQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0170').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSemkLHGzw35fYJQe8PNvnPbJF3-GWerILq4dwhw4VZGc2HD3w/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDIR1187').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf-vrjvKm7yG08AGui5CzidtbLHY033DMAgu1AnGL_dNkhluQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDIR1186').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScM2337bIXJ-ZbWmW7pzF1AqIbAu9wDjEf2ihfbmfmdxBSELA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDIR1190').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScplNrvoDuuBTsEz1rEDwvmwZ1qNH2nFIEj397vKk7_Lgi8DQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDIR1150').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdElD8CRu_cpS4OVeu38NorjyW6jMnUPH7LLXvwlnsQWwrSZg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0074').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScFCEL-O01wAWP7ttVnBA-1K2zxMwzMI7vOxaQqD4qrtKGCHw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0075').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeTwvQegRtwg1HFNbWNczqJEnqCbNnjSwQPJ36yr1gzmlrAkA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GSER1102').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe4gaI3hlcjaqkaayv0Sm7LwdM552jQIqGtU8GD9QujLsRFGQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDIR1176').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdk8YeWz6BBrR8CNfOrAL9FETqyWNxVCwREk_P560vUnzx14g/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0076').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdjm1ThD2aziCIwTM8DVU7CDYF6zDWz278egq77wCEL2VyLmg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0116').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeXfI1pOcxcbWenUY1Me2pY9taB6Fnvt9Afd6BEKbPOiJY7Nw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDMK0003').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSejv1pD3vSz1y6LNCLRuOTY78Jsqvu1XPvuqyfG6eH6yQIkjQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GGRH1046').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSd6g2K0sZf3TYlA1xYZwZeif1-CtV69XJIfz22ZZ_9i5ul11Q/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADM1068').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfcmE03El2f7J_o8LmmDqZMvw6tdrdw94KKLINlsIL2DDCj0g/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0129').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdGmezcb-bTzAd11onvbqioLeaXsf98bIsclnMom3x038p9xw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GCSA1055').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdRQ-32Hg9lSbx1TzUgBocVBoOqKlBGIEYaWLsbYSISTRgnpw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GADS1051').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScRldXzI13KQzP8TIhAm1q7FsacC2EpKl-sLxJJuwSm21WsQA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GRED1010').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSec0FLDJ6078VZuBQiFc7MzFVgSKpYYwBtDOmwxSX8gU6Jx4A/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GRED1009').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScTsl3aRWEVteHAGTUj5u_wvOszcifJ40AxRndlPUiizjVECQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GRED1004').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfBZ5eOF86Fs5gfRlHJ-Hr3KUJMNXtxD7WQDX-UKY-_xsatqg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GRED1003').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe7OE2h4xnPlvIVwFxft8GfGH6TM3KIjZP88X_uj3yYGMncsQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0143').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSejj7AS_D_kHIDuvkxIc5pOZ69brfzDYd4U9NF1qg81JyOLXQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0101').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfyoMrnnKbV1iiHftGWRhSKAppobr9t8QaRvOgTfkzTwxo1nA/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0202').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeBarKTQbM6w89Dj11NceiRzqOT7HR7kyWtyyIXfcaJCte6GQ/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDAI0005').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeP73fPcXL2fzkkSFSYjEDXPpOiN0pl40isGwdXuWeLlq10gw/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GEAD0205').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeSHfcjF-yBlDMucVBVjYenpm4I-3EwMjRlgIV8Fng2M58Swg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GDEF0007').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScw7JcrHbR8v7MHy6x_H3oiXRsSXZlYtjfj83hgRzCAYXy26g/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});
$('#GINS1003').click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeIQFtXs0ym-XifKoy5YnszXhH2nDaWGbxxuhqXxikRsLkdDg/viewform";var links = document.getElementById('links');links.className = "links";var prova = document.getElementById('prova');prova.className = "provaExibir";});