function mostrarSenha() {
    var str = document.getElementById("botaoMostrarSenha").innerHTML;
    var arr = str.split(" ");
    var res = arr[0];

    var campoAutenticacaoSenha = document.getElementById("senha");

    /* botaoMostrarSenha.innerHTML = "visibility_off"; */


    if (res == "visibility") {
        botaoMostrarSenha.innerHTML = "visibility_off";
        campoAutenticacaoSenha.setAttribute('type', 'text');
    }
    else {
        botaoMostrarSenha.innerHTML = "visibility";
        campoAutenticacaoSenha.setAttribute('type', 'password');
    }

}

function confirmar() {
    var senha = document.getElementById('senha').value;
    var arr = senha.split(" ");
    var camposenha = arr[0];

    var senhaDefinida = "#Uni123"

    if (camposenha == senhaDefinida) {
        var autenticacao = document.getElementById('autenticacao');
        autenticacao.className = "autenticacaoOcultar";

        var links = document.getElementById('links');
        links.className = "linksExibir";
    }
    else {
        window.alert("Prezado(a)!!\n\nVerifique se a senha digitada está correta.\nEm caso de dúvida entre em contato com a TE.\n\nE-mail: te@unisuam.edu.br")
    }

}

$("table input").keyup(function () {
    var index = $(this).parent().index();
    var nth = "table td:nth-child(" + (index + 1).toString() + ")";
    var valor = $(this).val().toUpperCase();
    $("table tbody tr").show();
    $(nth).each(function () {
        if ($(this).text().toUpperCase().indexOf(valor) < 0) {
            $(this).parent().hide();
        }
    });
});



var exibirProva = document.getElementById('exibirProva');

$("#GCSA1068").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdy3UACSo4SoeNi66-SKX7KTYS_HQefSBUef1SK2GZExBhZEA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCSA1055").click(function(){exibirProva.src = "https://docs.google.com/spreadsheets/d/1Qq8dG1-LQUO6jPDGUK5fI959RHC_AtctSKdVKaLtxSI/edit?resourcekey=undefined#gid=1038067279";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCOB1036").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeYy-oCP5IQcEOY2F2BZ16ZEuSCCqV6zNShsoROOGXTN0Mbww/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCSA1059").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScX9SNYwFFLP06-rDtcGiwcIUSyn7o0FpQ0SjkNJ9Z9JwSEMg/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GADM1078").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScKSPd5vqNu3mnXhDeI0R7znbr8FH5_gbX5ucIfOw5vDT9a3A/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCSA1062").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScDpSN4bTzdUZsf0nsbKrnT57R_qXCgaVUXrimrmt7zikRS6A/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GADM1074").click(function(){exibirProva.src = "https://docs.google.com/spreadsheets/d/1IU713w16CDAfnpfMRyFaGTf6CzUjXvDoeSVrKwL3OFM/edit?resourcekey=undefined#gid=996607768";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GADM1085").click(function(){exibirProva.src = "https://docs.google.com/spreadsheets/d/1yESRhEEowK_ZE7_TdVxDnz5mdzLGt5taKuaDLO8SUwc/edit?resourcekey=undefined#gid=381638000";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDEF0005").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdGq0IUcWVxTDuAa7Fh8m7T41z9DEQuXEJu3w2jcChr3zSomQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDEF0015").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeaHiaiX8_sAvmb0TmEWiYcF2votsS6RgljOdBuyLtN-kRT_A/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDEF0006").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeyPfw-syVk39yeOOi1kUZZLpCqK06uvwCppH4Raa6Af7gx1g/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCOB1073").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfjEGxEsDmBBHFSJ8rRKJIESZOR-2t3b7aljnhqadrNw6OUCQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCOB1077").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfACxvbR3kU3uJyfczX77gWNhllBXs-3ks3awRr0_SthYBl2g/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCOB1084").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdcG1yBA3Mi6qOAd7IYsJMtyOBBbzISWjXnsCglOvwHSSidQw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDEP0032").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdRySFcSwixaJei6xP3dQdvcQ-9bi-DpnmQB_8A5sWtkiybkQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDEP0001").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeO51OWQ4vjCivF-W9vx8h6XqE4EoKPtXkAHFh6r7-TZgRX-g/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GEAD0002").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScF8KrA2z7TICQS5KaQJUEp1px7SQuiWL4yQ-kuVH63He24Hw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GEAD0100").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfcgrwJwyIoNjMuR-QyCANgpehH5lE4VxUpVZZNhkbXVmQMGw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDEP0007").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfrQ2yP2x3Sw7oghRrjCRbO4CnEY0l-d6WCJSz1-nZ3oDWS1Q/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDEF0028").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdLoHgkNBWkYEaXFxEb0DaoKPnGSvV8hGGQCWOSad4F5P3fFg/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDEF0016").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdctTc6ceVqxQBq44E2LiVQ4uqr8hh6JUT64gDU9Tk4tz8FOA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDLH0001").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdv17wmzfu8jw2AbfRoG61W_UCbSjehEgCU1SbU_MyeEPKgEg/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDLH0004").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdeIylTgj-j3jfqi-NArnbVZMDhH4uDocZKZ71Ys5NJGNCiAA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDLH0006").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe-fh2BTL7fIChCV4vC8-jOu5wamM5JS7_8utld2IWkFEf-XA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDLH0012").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScy0pEw9dTlk1bpfvq_CPy_zj4TNdyCpyzmvKEQ5P5Z_gh2RA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDLL0001").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeVA9S17MxOLE4rudQqIR6mrrvwNsA4V1xIGXjVmko3oiqCWA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDLL0002").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdCpVA-ctXoH2MXi0rteVuO_cLkzRruJ-7IISbZH7ZhlvGcww/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDLL0006").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdpILaO_mE7Hg8_B0qv0kT4ad8LIPj1E1erAIQrvqvc_4ID2Q/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GPED1046").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSecyZG6uLWiFfrQPR7ExToWxeHwN5vymU7uwiGBfY7xDKl0Vw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GPED1054").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfjH3lD-S26kF5DbIXUAVHe4MlBQWVi_QzmhvVn4U4iPx39tg/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GPED1058").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfbuNlaqpPxSwNQjmxa0j0vaQKcBK6RTG8qijO2g9Fjo0ENiQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GPED1057").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeCQveI_d7z3AKDb-wD2WfxIMKE_1fxmHPIbJc-mpW9hlN9Cg/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GPED1181").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScQuI9kp18BxCAybvPb8N2F2b84Sy_oMgJhblGI3sOJaS_EqA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GPED1051").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfhlT9Hb3AfmMoTJ8p1v1Z6P_2FsJ5hhuPtJWHi6JG20qvzJA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GPED1123").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdiRR8Gv55bdNg0eO8pA2oWr2MEDbJhme7FxjBAH2ZcY-hc9A/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GPED1059").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScAeYsn0LljVm9S2sGW34--0SgkTCUhU1lUYEtrU8C5V6kCrw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GSER1097").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfGLuhA-ehxgxsuXam_M5IVosgqkwTGIUNRySqda7F773IFug/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GSER1098").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScwvmf2CnWmp28mJbfbqJMDB4Z5_EIAC3xytptZhRucu6_ylQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GSER1039").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfUZq1NDLn89bdskcE732GP8a-gBglIiINmcCKPQ-rczN5VRw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GSER1103").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeoE-moIaF6WieXzTmum7XeoUeFBXCl6wK85YL8-vozRMs-Ug/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GSER1045").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScUTgfFwnxyjHSaf3lu_1z1Ye96AsGgfg2XdfTeFJ6HB1SaBw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GSER1051").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf4LHdvYh9dUWE8umfQETDLx0kBf_nG9DuKpXN0XrFwVH3I2w/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GSER1056").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe9vvTOymD2LTKq2IOU3vQN5JIL2DKDuYYVm0jvepy7Sf_P-g/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GLET1036").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeeCAZ6RwKLhbDgzUJhUhMy-jGY5z9s43zYL6oJ93N9GGFNkg/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GENG1068").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf_bcOwLh6IwCaWEnKEUd2f6u3NxkSonWGHsqJ-gbrL4tcKhA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GADS1049").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScWBZRJgeBsiAjM7o7u_dTpaMuFCqLPD1KgqNxbBMQZlQPXDg/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GADS1060").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfvCuroHRXsAJfPtqRC_iTGW3XMOl_Eqjc-p22H9DMieqqG4Q/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GADS1061").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdUEFZS0xnIbcJsaigFKmC5IZSOez2AvivI52BOct9gqZekgQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDAI0002").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf_2FkCRRcvTtwZwhL1J5ijzDTCnEkMNtHE34qplmkfQ8wFBw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDAI0004").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfdneTjfK7YGTURYt7bVwFQJ3a51FuUmk1jb7ppUfobIrMKlA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDAI0007").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdss62dOLZb0KHjb6a-gZQ62pouJU6UfLUQ901f-9a8byKpYg/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GGAM1015").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfbJisMKMAlGTvX5fJMvSVJDzE8uK0pmYjWGEdMpLCeW7iJtQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GGAM1019").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSes160SnaUBjSXcPVjJ4uqH421EgRBtOFkMGLoIFFoQRnEBRg/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GGAM1021").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSecyBmFRVdOAfoYL4cvTKRd64PzIM_c0SZ7Bbh3bvCftPoWFw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GGAM1025").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf1EjLmdaKpAUD0moqVvNiZ2hbAt3IvejwEC120v39zZgGRXQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GGAM1027").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdBMZAak-DS9eKkFqJnXsCqQ-qI3hgqyC7IbJoyhWdQnGTkmA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCSA1011").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdBPPNCS9Obh_5VDdvG-6Zy4h5MqajwvycFLZ_5Oce2m9Diug/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GADM1096").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScTWNRovlk9p7cG1J6ipxWiWt_4tEvF8mXpK8I9-4Nj9SqSvw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GADM1097").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeQZckGhb8KJj01u3fwTjEvccQGw_nxh_evN4BxbsebPmofPQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GMKT1072").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe0UXALq1JM0Ms-CxhYh-t7cPmoAXU1k5GXiIPWKfYMaAlbAg/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GADM1099").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf4Ho5rXI_0lSDPjRkelw64R-fT2gt3c2LQN15K4pwvd3a0aQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GPSI1074").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSd1rTZ3O6PLiI5GIDWAmCrd3roNZIZ6hkTXy2xQAYfpcXQ_ew/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GGRH1045").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeq6f3DCD_v1sgfsPnGBqsIuSJ7rLhK80xnbX-BmFqz7t9zkg/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GGRH1048").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSceK4qMnQXb0a62dQ4dEB55yjU-peABFOd2p2W7yM8jogBB6A/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GGRH1049").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfhy35KsXdAV3APRdt5SC2Sovnv_LWtUIZJsAxDGWTYKYuetw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDPU0003").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScjFxUUIdaVNhaTbMU54S7TckjEac55HNtp8DfdaDftdY6J8g/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDPU0017").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScIVirgLpFQpm8lYDKC-aD9PAjve0vRcfXuT6a8x22WVKKByg/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDIR1177").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSe8EkCZroxeC9z19_SwoXKAXn0DCZ5lavldMtiG-SyEN2o5gw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDIR1181").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeETLyoJYDvf2bi2ohf5nbxuORmjubDq65DEIxQ2L4FmAhsTQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDIR1182").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScaBW9QYUYX4gEzmiBNNIXrZAMQk326iMeOrMd5gh55DX-CuA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDIR1186").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScM2337bIXJ-ZbWmW7pzF1AqIbAu9wDjEf2ihfbmfmdxBSELA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GECO1023").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf2zbDXBSm52rEJxOeZRp0HEuqBqWOR5MFRjQq8OGBW_HiyRA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCOB1038").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfbGgpM0BaTCm_K-RTtoaIzqeh68qoxH8Et4GG7gMc2qahe0w/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCOB1041").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSePpDp1mK_LEuwDhOJMLdhM9wOzt4UAclC5DAHeMTiPASSdfw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCOB1045").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfYNx5q_yObAfCUMyNYpBEb5ZUKyFYjjBwY5DGKh5zUZF6arw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCOB1048").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfzoX4V29UxvCtJuEA7O5iJXlswnZQgcA_ho3yyUQsXkahd5Q/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GGHO0002").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfZkslwfi6gMBPQagNkoNIvHZLd51nNRposR2IW5Fw-m_5--g/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GGHO0007").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfUPT2Vv94MJlq8Eb9ItyOISIfvxFE0gaDQcSxEeDSv9eZSjQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GGHO0008").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdvLpjFFqRWd1eS4tTOuETka7Al-DCPJZktwqw-fDnXowefXQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GGHO0010").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeQ1N37Lt7U6uu2lzTkq87BliN7xCRW9YkTJZ3rimLZVIsLHQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCSA1035").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdg8wWVHtceZoJrt1-rR16lgdWmhVBmMlfwvU9EfPCSu2IeQg/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCSA1038").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfnTrmD_e2piGNJGOa5AvANY5n-O075t2vd7kSFbftA2Rfx9w/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCSA1040").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSfnluWekYEUCHXWkZiHCVzhjpf9YeompzhFvqJUDLNrIV8-sA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCSA1041").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSemhyi7BP28dfHInWAoxqx0vs5onRqayuvebpuMntrB5L2hkg/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GCSA1049").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeFK0VwXq4YC4QOSSIXDHu6Zhlhh9Wuhgk2WF6BehPO1JsghA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDLO0003").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeSqmJlHci_yyFcy2HxGzHIWGiACbOhFszoiRrNynes4Xp1Yw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDLO0004").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScng0pb1wyGltrOyF9nlgdbNEyF3Mmwcef1iSiEoNYQBLYqZw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GEAD0027").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScmQ3gceharUds7XSfRjSR6W56KbSrrL4mt1WZMu1jpJaQz0A/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GEAD0131").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLScNFGSzBaJKLzf0r7OdhB52um6GsTJqQVZApwYSlwyIOMcrHw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GDMK0015").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSf1jHd19GSAtKXhE7D7uF3WJkiXzEVQpOL7erPosV3yjkrZ7g/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GMKT1046").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdNbnqj12beYqgX4RfmgN2OF3J2amVETwl5ME-yB7-x-97iGA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GADM1038").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdIsIEqToeW5pRI3qW6WKigs_C1AL3qEsKPBxb0XGRotpOz4g/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GADM1041").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSc_ToKryOGLuypaUFhSoNp9FrsBAT4RGxzPKSNY6iEgc86y_A/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GPRO1045").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdOeCSFf0dzjpSyKyMRTtvO5a3Ng6Bdt0Rkp44GVxf6fWQ2AQ/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GADS1056").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSffFb3CYoebsr_Sen9n6S5PIGXznJs0xqd70W31MPZJbTFCGw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GINF1025").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeJffz5FFJskFnXyxoaVM30scWgkEJSxErdVa0z190BoNVKlA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GRED1008").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSdMAbF9aTaQ2n2ydjx2CCLaffkoTCHG9ywSuKnugXAFpy87Hw/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});
$("#GADM1085").click(function(){exibirProva.src = "https://docs.google.com/forms/d/e/1FAIpQLSeJ0KPYeF0Trlwttx0VfIEckMAMwFAgqphSNW9khzb6bvX2IA/viewform";var links = document.getElementById("links");links.className = "links";var prova = document.getElementById("prova");prova.className = "provaExibir";});